set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN T1 [get_ports melody]
set_property PACKAGE_PIN U4 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports melody]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN P5 [get_ports {sw[7]}]
set_property PACKAGE_PIN P4 [get_ports {sw[6]}]
set_property PACKAGE_PIN P3 [get_ports {sw[5]}]
set_property PACKAGE_PIN P2 [get_ports {sw[4]}]
set_property PACKAGE_PIN R2 [get_ports {sw[3]}]
set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
set_property PACKAGE_PIN N4 [get_ports {sw[1]}]
set_property PACKAGE_PIN R1 [get_ports {sw[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
set_property PACKAGE_PIN R3 [get_ports {button[2]}]
set_property PACKAGE_PIN T3 [get_ports {button[1]}]
set_property PACKAGE_PIN T5 [get_ports {button[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports sd]
set_property PACKAGE_PIN M6 [get_ports sd]


set_property IOSTANDARD LVCMOS33 [get_ports {ledrange[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledrange[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledrange[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledsw[0]}]
set_property PACKAGE_PIN L1 [get_ports {ledrange[2]}]
set_property PACKAGE_PIN M1 [get_ports {ledrange[1]}]
set_property PACKAGE_PIN K3 [get_ports {ledrange[0]}]
set_property PACKAGE_PIN F6 [get_ports {ledsw[7]}]
set_property PACKAGE_PIN G4 [get_ports {ledsw[6]}]
set_property PACKAGE_PIN G3 [get_ports {ledsw[5]}]
set_property PACKAGE_PIN J4 [get_ports {ledsw[4]}]
set_property PACKAGE_PIN H4 [get_ports {ledsw[3]}]
set_property PACKAGE_PIN J3 [get_ports {ledsw[2]}]
set_property PACKAGE_PIN J2 [get_ports {ledsw[1]}]
set_property PACKAGE_PIN K2 [get_ports {ledsw[0]}]
