set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN T1 [get_ports melody]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports melody]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN P15[get_ports reset]



set_property IOSTANDARD LVCMOS33 [get_ports sd]
set_property PACKAGE_PIN M6 [get_ports sd]













set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN G2 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bg_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_l[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_sw[0]}]
set_property PACKAGE_PIN G4 [get_ports {bg_led[6]}]
set_property PACKAGE_PIN G3 [get_ports {bg_led[5]}]
set_property PACKAGE_PIN J4 [get_ports {bg_led[4]}]
set_property PACKAGE_PIN H4 [get_ports {bg_led[3]}]
set_property PACKAGE_PIN J3 [get_ports {bg_led[2]}]
set_property PACKAGE_PIN J2 [get_ports {bg_led[1]}]
set_property PACKAGE_PIN K2 [get_ports {bg_led[0]}]
set_property PACKAGE_PIN P5 [get_ports {bg_sw[7]}]
set_property PACKAGE_PIN P4 [get_ports {bg_sw[6]}]
set_property PACKAGE_PIN P3 [get_ports {bg_sw[5]}]
set_property PACKAGE_PIN P2 [get_ports {bg_sw[4]}]
set_property PACKAGE_PIN R2 [get_ports {bg_sw[3]}]
set_property PACKAGE_PIN M4 [get_ports {bg_sw[2]}]
set_property PACKAGE_PIN N4 [get_ports {bg_sw[1]}]
set_property PACKAGE_PIN R1 [get_ports {bg_sw[0]}]
set_property PACKAGE_PIN F6 [get_ports {bg_led[7]}]
set_property PACKAGE_PIN B4 [get_ports {seg_sel_l[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_sel_l[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_sel_l[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_sel_l[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_sel_l[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_sel_l[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_sel_l[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_sel_l[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg_sel_r[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg_sel_r[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg_sel_r[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg_sel_r[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg_sel_r[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg_sel_r[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg_sel_r[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg_sel_r[0]}]
set_property PACKAGE_PIN K1 [get_ports {sm_led[7]}]
set_property PACKAGE_PIN H6 [get_ports {sm_led[6]}]
set_property PACKAGE_PIN H5 [get_ports {sm_led[5]}]
set_property PACKAGE_PIN J5 [get_ports {sm_led[4]}]
set_property PACKAGE_PIN K6 [get_ports {sm_led[3]}]
set_property PACKAGE_PIN L1 [get_ports {sm_led[2]}]
set_property PACKAGE_PIN M1 [get_ports {sm_led[1]}]
set_property PACKAGE_PIN K3 [get_ports {sm_led[0]}]
set_property PACKAGE_PIN U3 [get_ports {sm_sw[7]}]
set_property PACKAGE_PIN U2 [get_ports {sm_sw[6]}]
set_property PACKAGE_PIN V2 [get_ports {sm_sw[5]}]
set_property PACKAGE_PIN V5 [get_ports {sm_sw[4]}]
set_property PACKAGE_PIN V4 [get_ports {sm_sw[3]}]
set_property PACKAGE_PIN R3 [get_ports {sm_sw[2]}]
set_property PACKAGE_PIN T3 [get_ports {sm_sw[1]}]
set_property PACKAGE_PIN T5 [get_ports {sm_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports btn_center]
set_property IOSTANDARD LVCMOS33 [get_ports btn_down]
set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property IOSTANDARD LVCMOS33 [get_ports btn_up]
set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property IOSTANDARD LVCMOS33 [get_ports pwm]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN R15 [get_ports btn_center]
set_property PACKAGE_PIN R17 [get_ports btn_down]
set_property PACKAGE_PIN V1 [get_ports btn_left]
set_property PACKAGE_PIN R11 [get_ports btn_right]
set_property PACKAGE_PIN U4 [get_ports btn_up]
set_property PACKAGE_PIN T1 [get_ports pwm]
set_property PACKAGE_PIN P15 [get_ports rst]
