# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/86138/Documents/Piano_complete/piano.cache/wt [current_project]
set_property parent.project_path C:/Users/86138/Documents/Piano_complete/piano.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/86138/Documents/Piano_complete/piano.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/ppppparameters.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/account.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/auto_play.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/auto_tubs.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/autoplay_led.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/clock1.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/clock2.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/debounce.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/debounce2.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/debounce3.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/free_play.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/free_play_top.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/free_tubs.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/generate_melody.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/learn_mode.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/learn_song1.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/learn_song2.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/learnmode_7seg.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/led.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/music_to_frequency.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/recording.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/show_mode.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/song1.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/song2.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/song3.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/store_music.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/tubes_display.v
  C:/Users/86138/Documents/Piano_complete/piano.srcs/sources_1/new/top_module.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/86138/Documents/Piano_complete/piano.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/86138/Documents/Piano_complete/piano.srcs/constrs_1/new/top.xdc]


synth_design -top top_module -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
